### ISSUE TITLE
Remove unnecessary functions

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/uvcombine#26]
Remove unimplemented/unused code:
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L177
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L256
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L281
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L444
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L460
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L476
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L494
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L512
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L535
 * [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L607

**Comment by e-koch** [comment]
All of these should have been removed or deprecated in #28
