### ISSUE TITLE
Refactor to use only not-agpy tools

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/uvcombine#27]
These tools aren't maintained and should be replaced:

* [ ] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L1071
* [x] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L1022
* [x] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L19
* [x] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L1259-L1260 -> can clearly use spectral-cube here
* [x] https://github.com/radio-astro-tools/uvcombine/blob/3bb3f674977c262709a0593ad468c13c5daa2f2e/uvcombine/uvcombine.py#L1338

**Comment by e-koch** [comment]
at some point this got addressed: https://github.com/radio-astro-tools/uvcombine/blob/d05bd34b0b4d14fae846dae19d9195ac515be254/uvcombine/uvcombine.py#L738
